### ISSUE TITLE
[BUG] 소셜 로그인 후 AuthCheck 에러

### ISSUE THREAD

**Issue by joonwonBaek** [Team-E2I4/Team-E2I4-TiKiTaza-FE#105]
### Current Behavior:

https://github.com/Team-E2I4/Team-E2I4-TiKiTaza-FE/assets/44563138/cd01deba-da06-4747-be23-fe7c6d172977

소셜 로그인 성공 후 `/main`으로 이동할 때 위와 같은 에러가 발생합니다..

### Expected Behavior:

버튼 클릭 후 => 로그인 과정 => 로그인 성공하면 token이 LocalStorage에 저장되고 `/main`으로 이동
### Steps To Reproduce:

1. `.env` 파일 추가
1. `yarn run dev` 실행
1. `/login` 라우트로 이동
1. 카카오 로그인 버튼 클릭

### Environment:

- OS: Windows11
- Node: 20.8.1
- npm: 10.1.0

**Comment by loevray** [comment]
버그 해결되셨으면 클로즈 해주세용~!
