### ISSUE TITLE
[Fix] UI 개선 - game autofocus

### ISSUE THREAD

**Issue by dlsxjzld** [Team-E2I4/Team-E2I4-TiKiTaza-FE#236]
### 📋 개요
라운드가 시작하면서 타이머가 종료되었을 때 input창에 autoFocus가 되도록 합니다

### 💻 ToDoList
- [x] 라운드 타이머 끝나면 입력창에 autoFocus

**Comment by yejinleee** [comment]
요거 UI개선 Stlye 이슈에 PR 보내두 되지 않을까요!!? 👀
