### ISSUE TITLE
[Fix] 인게임 중 이탈한 유저 방생성시 '수정'문구 

### ISSUE THREAD

**Issue by yejinleee** [Team-E2I4/Team-E2I4-TiKiTaza-FE#244]
### 📋 개요
인게임 중 이탈한 유저 방생성시 방생성모달에 '생성' 이 아닌 '수정' 이라고 뜨는 이슈 해결

### 💻 ToDoList
- [ ]

**Comment by dlsxjzld** [comment]
인게임 중 이탈한 유저 방생성시 '수정' 문구가 뜨지 않는데 어떤 상황에서 되는지 알려주실 수 있을까요?! 👀
