### ISSUE TITLE
[Fix] 게임 시작후 뒤로가기버튼으로 나갈시 roomInfoStore초기화 못하는 버그 수정

### ISSUE THREAD

**Issue by loevray** [Team-E2I4/Team-E2I4-TiKiTaza-FE#261]
### 📋 개요

게임 시작후 뒤로가버튼으로 나갈 시 roomInfoStore초기화 못하는 버그를 수정합니다.

### 💻 ToDoList
- [ ] roomInfoStore를 잘 초기화 해봅니다..!!

### 🔍 point
어디에서 초기화 할 것인가?🤔

**Comment by dlsxjzld** [comment]
혹시 이거 예진님이 해주시지 않았나요?!?! 🤔
