### ISSUE TITLE
[fix] 웹소켓 쌓임 현상 해결

### ISSUE THREAD

**Issue by dlsxjzld** [Team-E2I4/Team-E2I4-TiKiTaza-FE#308]
### 📋 개요
연속되는 게임 진행 시 websocket이 쌓이는 현상 해결
![스크린샷 2024-03-20 00 09 14](https://github.com/Team-E2I4/Team-E2I4-TiKiTaza-FE/assets/66900221/b69df55d-8169-46a3-ab06-45a51a86f0a1)

### 💻 ToDoList
- [ ] 연속되는 게임 진행 시 websocket이 쌓이는 현상 해결

**Comment by loevray** [comment]
이미 연결이 존재하면 연결하지 않는 방향으로 가야할까요?!

**Comment by dlsxjzld** [comment]
subscribe을 한번 더 하면 안될 것 같은데 고민이네요 ㅎㅎ
