### ISSUE TITLE
[Fix] GamePage 수정

### ISSUE THREAD

**Issue by dlsxjzld** [Team-E2I4/Team-E2I4-TiKiTaza-FE#91]
### 💻 ToDoList
- [x] GamePage의 isKicked 수정 -> useAuthCheck에서 userId 받아오기
- [x] 일반 유저 강퇴 시 해당 [warning](https://velog.io/@pon06188/Warning-Cannot-update-a-component-A-while-rendering-a-different-component-B.-To-locate-the-bad-setState-call-inside-B-follow-the-stack-trace-as-described-in-%EC%97%90%EB%9F%AC-%ED%95%B4%EA%B2%B0) 나옴 -> useEffect로 navigate 로직 wrapping 하기
- [x] useAuthCheck가 GameWaitingRoom에서도 반복됨 -> GamePage로 이동

### 🔍 point

* useAuthCheck가 반복되어서 GameWaitingRoom에 있던 로직들을 GamePage로 이동시켰습니다. 괜찮을까요?!
* 일반 유저 강퇴 시 warning이 나와서 해당 warning을 처리하려면 useEffect 로 감싸야 한다고 해서 navigate하는 로직들을 useEffect로 감쌌습니다. 
useEffect를 if문 아래에서 호출할 수 없기에 이렇게 두었는데 괜찮을까요?!

**Comment by yejinleee** [comment]
> useAuthCheck가 반복되어서 GameWaitingRoom에 있던 로직들을 GamePage로 이동시켰습니다. 괜찮을까요?!

그럼 게임 컴포넌트마다 확인하는게 아니라 라우트 변경시(/game 전체에서 한번하니까?) 에 검사가 되는 것 같은데, 그 용도가 맞을까요 ?
